Demonstrating bug
Error: The plugin "gatsby-source-prismic" created a node of a type owned by another plugin.
        The node type "File" is owned by "gatsby-source-filesystem".
        If you copy and pasted code from elsewhere, you'll need to pick a new type name
        for your new node(s)